export const colorOptions = [
  { value: "#b8256f", label: "Rouge cerise" },
  { value: "#db4035", label: "Rouge" },
  { value: "#ff9933", label: "Orange" },
  { value: "#fad000", label: "Jaune" },
  { value: "#afb83b", label: "Vert olive" },
  { value: "#7ecc49", label: "Vert citron" },
  { value: "#299438", label: "Vert" },
  { value: "#70c4bf", label: "Vert menthe" },
  { value: "#158fad", label: "Bleu canard" },
  { value: "#14aaf5", label: "Bleu ciel" },
  { value: "#96c3eb", label: "Bleu clair" },
  { value: "#4073ff", label: "Bleu" },
  { value: "#884dff", label: "Raisin" },
  { value: "#af39eb", label: "Violet" },
  { value: "#eb96eb", label: "Lavande" },
  { value: "#fc76a1", label: "Magenta" },
  { value: "#ff8d85", label: "Saumon" },
]

export const iconOptions = [
  { value: "ri-graduation-cap-fill", label: "Chapeau", icon: "\\f332" },
  { value: "ri-mail-fill", label: "Enveloppe", icon: "\\eef3" },
  { value: "ri-home-2-fill", label: "Maison", icon: "\\ee18" },
  { value: "ri-archive-fill", label: "Archive", icon: "\\ea47" },
  { value: "ri-award-fill", label: "Médaille", icon: "\\ea89" },
  { value: "ri-bar-chart-2-fill", label: "Statistiques 1", icon: "\\ea95" },
  { value: "ri-pie-chart-2-fill", label: "Statistiques 2", icon: "\\eff5" },
  { value: "ri-bookmark-fill", label: "Marque", icon: "\\eae4" },
  { value: "ri-calendar-fill", label: "Calendrier", icon: "\\eb26" },
  { value: "ri-briefcase-4-fill", label: "Sac", icon: "\\eaf0" },
  { value: "ri-chat-4-fill", label: "Chat", icon: "\\eb52" },
  { value: "ri-pencil-fill", label: "Stylo", icon: "\\efdf" },
  { value: "ri-pencil-ruler-fill", label: "Stylo-Règle", icon: "\\efe3" },
  { value: "ri-tools-fill", label: "Outils", icon: "\\f21a" },
  { value: "ri-bug-fill", label: "Virus", icon: "\\eb06" },
  { value: "ri-terminal-box-fill", label: "Terminal", icon: "\\f1f5" },
  { value: "ri-computer-fill", label: "Ordinateur", icon: "\\ebc9" },
  { value: "ri-phone-fill", label: "Téléphone", icon: "\\efe9" },
  { value: "ri-database-2-fill", label: "Serveur", icon: "\\ec15" },
  { value: "ri-keyboard-box-fill", label: "Clavier", icon: "\\ee72" },
  { value: "ri-file-3-fill", label: "Page", icon: "\\ecc4" },
  { value: "ri-clipboard-fill", label: "Presse-Papiers", icon: "\\eb90" },
  { value: "ri-bank-card-2-fill", label: "Cart", icon: "\\ea8f" },
  { value: "ri-price-tag-3-fill", label: "Etiquette", icon: "\\f022" },
  { value: "ri-shopping-cart-2-fill", label: "Caddie", icon: "\\f11d" },
  { value: "ri-trophy-fill", label: "Trophée", icon: "\\f22e" },
  { value: "ri-gift-2-fill", label: "Cadeau", icon: "\\edb8" },
  { value: "ri-24-hours-fill", label: "24h", icon: "\\ea01" },
  { value: "ri-capsule-fill", label: "Médicament", icon: "\\eb36" },
  { value: "ri-map-pin-2-fill", label: "Position", icon: "\\ef09" },
  { value: "ri-car-fill", label: "Voiture", icon: "\\eb38" },
  { value: "ri-camera-fill", label: "Caméra", icon: "\\eb2e" },
  { value: "ri-music-2-fill", label: "Musique", icon: "\\ef82" },
  { value: "ri-headphone-fill", label: "Casque", icon: "\\ee04" },
  { value: "ri-notification-fill", label: "Notification", icon: "\\ef99" },
  { value: "ri-equalizer-fill", label: "Réglage", icon: "\\ec9c" },
  { value: "ri-apps-fill", label: "App", icon: "\\ea43" },
  { value: "ri-alarm-fill", label: "Réveil", icon: "\\ea1a" },
  { value: "ri-account-box-fill", label: "Personne", icon: "\\ea06" },
  { value: "ri-basketball-fill", label: "ballon", icon: "\\eaa7" },
]
